spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
        - id: item-service
          uri: lb://item-service
          predicates:
            - Path=/item-service/**
        - id: borrow-service
          uri: lb://borrow-service
          predicates:
            - Path=/borrow-service/**
#        - id: cart-service
#          uri: lib://cart-service
#          predicates:
#            - Path=/cart-service/**
server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  # Gateway routes configuration
logging:
  level:
    root: debug