minio:
  bucketName: item-pic
  endpoint: http://101.200.15.215:9000
  accessKeySecret: Okyq4TLNem6fQIUGPExKHkLWTbajfggzbqOZei8b
  accessKeyId: hkpuh4lgK40WQJTotoan

server:
  port: 8082


spring:
  application:
    name: item-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.200.15.215:3306/item-management
    username: root
    password: fly142857


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true


logging:
  level:
    root: debug